import pygame
import time
import math



SCREEN_WIDTH =  700
SCREEN_HEIGHT = 700

NUMBER_FLOORS = 10
NUMBER_ELEVATORS = 4

FLOOR_HEIGHT = SCREEN_HEIGHT//NUMBER_FLOORS
FLOOR_WIDTH = 100

BUTTON_WIDTH = FLOOR_WIDTH//4
BUTTON_HEIGHT = (FLOOR_HEIGHT+20)//2#(68*FLOOR_HEIGHT)//100
BUTTOM_SPACE = 7

ELEVATOR_H = FLOOR_HEIGHT - BUTTOM_SPACE
ELEVATOR_W = ELEVATOR_H

BUILDING_POSITION_WIDTH = SCREEN_WIDTH//100*10
BUILDING_POSITION_HEIGHT = 0

BUTTON_COLOR = (0, 255, 0)
BUTTON_PRESSED_COLOR = (255, 0, 0)

FONT_SIZE = 12


TIME_PASS_FLOOR = 0.5
TIME_STOP_FLOOR = 2

